Calculate average function
MIT-Emerging-Talent/ET6-foundations-group-12 pull request #11
Opened 2024-12-26 17:12 UTC by Yevheniia-Rudenko

---
name: solution review 
about: A template PR for code review with a checklist
---

## Behavior

### Files

- [ ] The file name describes the function's behavior
- [ ] There is a module docstring in the function file
- [ ] The test file's name matches the function file name -
  `/tests/test_file_name.py`
- [ ] There is a module docstring in the tests file

### Unit Tests

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Every unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
  - [ ] There is no logic in the unit test
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases

### Function Docstring

- [ ] The function's behavior is described
- The function's arguments are described:
  - [ ] Type
  - [ ] Purpose
  - [ ] Other assumptions (eg. if it's a number, what's the expected range?)
- The return value is described
  - [ ] Type
  - [ ] Other assumptions are documented
- The defensive assertions are documented using `Raises:`
  - [ ] Each assumption about an argument is checked with an assertion
  - [ ] Each assertion checks for _only one_ assumption about the argument
- [ ] Include 3 or more (passing!) doctests

### The Function

- [ ] The function's name describes it's behavior
- [ ] The function's name matches the file name
- [ ] The function has correct type annotations

## Strategy

### Do's

- [ ] Variable names help to understand the strategy
- [ ] Any comments are clear and describe the strategy
- [ ] Lines of code are spaced to help show different stages of the strategy

### Don'ts

- [ ] The function's strategy _is not_ described in the documentation
- [ ] Comments explain the _strategy_, **not** the _implementation_
- [ ] The function _does not_ have more comments than code
  - If it does, consider finding a new strategy or a simpler implementation

## Implementation

- [ ] The code passes the formatting checks
- [ ] The code passes all Ruff linting checks
- [ ] The code has no (reasonable) Pylint errors
  - In code review, you can decide when fixing a Pylint error is helpful and
    when it's too restricting.
- [ ] Variables are named with snake_case
- [ ] Variable names are clear and helpful
- [ ] The code follows the strategy as simply as possible
- [ ] The implementation is as simple as possible given the strategy
- [ ] The code includes defensive assertions
- [ ] Defensive assertions include as little logic as possible

2024-12-26 17:14 UTC, Yevheniia-Rudenko commented
Hi everyone! This is my first attempt of the pull request. Could someone please review my code?

2024-12-26 22:14 UTC, Awaab98 commented
I will take on the review process.

2024-12-26 22:21 UTC, Awaab98 commented
Lets start with the CI checks, then I will comment on the code. We have three CI checks on push, and three simillar ones on the PR, which did not pass. This means that we only have to pass three checks. I have some suggestions for each one.

2024-12-26 22:29 UTC, Awaab98 commented
As for the first faild check: **md_formating**, you can solve this by going to **collaboration/guide/0_repository_setup.md** file in your branch repository, **line 17**, and break the line into two lines since its length is 132, which is more than the maximum expected line length of 80. This way the **md_formating** check will pass.

2024-12-27 09:28 UTC, Awaab98 commented
Now, for the both **py_formatting** faild checks, install **ruff** locally. Then use the command: **ruff check file.py** to ensure that both the function and the tests are compliant with ruff's linting standards. Once the checks pass locally, commit and push the changes, and the CI check will pass.

2024-12-27 17:16 UTC, Yevheniia-Rudenko commented
@Awaab98 Thank you so much for your review and your suggestions! I will work on addressing the CI checks!! I’ll let you know as soon as I do any changes.

2024-12-27 19:57 UTC, Allukmon commented
This is really helpful, I am able to get some meaningful insight that will help me.

Thanks a lot @Yevheniia-Rudenko @Awaab98

2024-12-28 19:21 UTC, Awaab98 commented
@Yevheniia-Rudenko I have updated your pull request with the latest changes from main. Now, it is **8/10** on the CI checks you only need to work on the the **py_formating**  CI check as I explanied in the previous comments.

2024-12-29 13:44 UTC, Yevheniia-Rudenko commented
I tried to update ruff to the latest version to use the --fix option for automatically fixing code formatting. The installed version (0.8.4) doesn't support it. However, all ruff checks on my local machine worked fine, and the code is correctly formatted locally.

When I tried to install the latest version from GitHub, I got an error because Rust and Cargo are not installed. I will install Rust and Cargo, then try installing ruff again and check for the --fix option.

2024-12-29 14:02 UTC, Awaab98 commented
@Yevheniia-Rudenko. You are right. I have updated your pull request with the latest changes from main after the latest changes introduced by Evan to the settings.json, commit: 8e42c8768ebeadede5391f31dc632e3693f995f2 , **use ruff as formatter**. Still, the two checks relating to **py_formatting** faild. This issue is related to the formatting of the both `.py` files, hence, I will check your files and suggest the solving changes accordingly.

2024-12-29 15:46 UTC, Awaab98 commented
@Yevheniia-Rudenko. **Good news!** I was able to figure out a solution to the **py_formating** CI CHECK. You can find the suggested changes as comments to the respective lines on both the function and the test files. Once you integrate the suggested changes, the aforementioned check will succeed.

2024-12-29 16:07 UTC, Yevheniia-Rudenko commented
@Awaab98, the CI checks issue is finally resolved—it was easier than I expected! I updated pip and ruff and ran the ruff format command. Thank you so much for your help and guidance!

2024-12-29 16:17 UTC, Awaab98 commented
@Yevheniia-Rudenko Thats great. I see that you have made some changes to the **settings.json** file. I suggest that you consider the changes to the empty lines that I have made because they allow you to pass the **py_formatting** check without the need to change the setting.json file. You can find my detailed suggestions on the **files changed** tab.

2024-12-29 16:49 UTC, Yevheniia-Rudenko commented
@Awaab98, all done—I reverted to the initial VS Code settings, and the CI checks are still passing. Thanks for your suggestions and support! 🙌

2025-01-02 22:48 UTC, Awaab98 requested changes
@Yevheniia-Rudenko I have suggested some changes as you can see under the files changed section.

2025-01-03 14:38 UTC, Yevheniia-Rudenko commented on solutions/calculate_average.py
Thank you for pointing this out! I have removed all unnecessary indentations on empty lines to ensure the file adheres to proper formatting standards and passes the Ruff check.

2025-01-03 14:38 UTC, Yevheniia-Rudenko commented on solutions/calculate_average.py
> +def calculate_average(num1: float, num2: float) -> float:
Agreed. I'll update num1 to the_first_number and num2 to the_second_number throughout the code and documentation in the next commit.

2025-01-03 14:39 UTC, Yevheniia-Rudenko commented on solutions/calculate_average.py
> +
Adding an Examples section is a good idea. It will be included in the function docstring in the next commit.

2025-01-03 14:40 UTC, Yevheniia-Rudenko commented on solutions/calculate_average.py
> +        AssertionError: if any argument is not a number
TypeError is more appropriate for type validation, you are right. This change will be implemented in the next commit.

2025-01-03 14:40 UTC, Yevheniia-Rudenko commented on solutions/tests/test_calculate_average.py
> +
I will add the summary for the test categories of the test module in the next commit.

2025-01-03 14:48 UTC, Yevheniia-Rudenko commented
Hello, @Awaab98 Thank you so much for your comments, it was really helpful! I pushed some changes based on your review, could you please take a look? 55581a456ce2f8fb6ba43e2e27103a1a3f0a3aaa

2025-01-03 17:24 UTC, Awaab98 commented
fj

2025-01-03 17:34 UTC, Awaab98 approved these changes
Yes. That is great. I have checked the changes that you implemented. Everythings stands in order, and I am going to merge the pull request.

2025-01-03 17:34 UTC, merged

2025-01-04 13:19 UTC, Yevheniia-Rudenko commented
Thank you @Awaab98 !