Update solutions
MIT-Emerging-Talent/ET6-foundations-group-12 pull request #25
Opened 2024-12-29 13:08 UTC by Allukmon

---
name: solution review 
about: A template PR for code review with a checklist
---

# Behavior

## Files

- [ ] The file name describes the function's behavior
- [ ] There is a module docstring in the function file
- [ ] The test file's name matches the function file name -
  `/tests/test_file_name.py`
- [ ] There is a module docstring in the tests file

### Unit Tests

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Every unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
  - [ ] There is no logic in the unit test
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases

### Function Docstring

- [ ] The function's behavior is described
- The function's arguments are described:
  - [ ] Type
  - [ ] Purpose
  - [ ] Other assumptions (eg. if it's a number, what's the expected range?)
- The return value is described
  - [ ] Type
  - [ ] Other assumptions are documented
- The defensive assertions are documented using `Raises:`
  - [ ] Each assumption about an argument is checked with an assertion
  - [ ] Each assertion checks for _only one_ assumption about the argument
- [ ] Include 3 or more (passing!) doctests

### The Function

- [ ] The function's name describes it's behavior
- [ ] The function's name matches the file name
- [ ] The function has correct type annotations

## Strategy

### Do's

- [ ] Variable names help to understand the strategy
- [ ] Any comments are clear and describe the strategy
- [ ] Lines of code are spaced to help show different stages of the strategy

### Don'ts

- [ ] The function's strategy _is not_ described in the documentation
- [ ] Comments explain the _strategy_, **not** the _implementation_
- [ ] The function _does not_ have more comments than code
  - If it does, consider finding a new strategy or a simpler implementation

## Implementation

- [ ] The code passes the formatting checks
- [ ] The code passes all Ruff linting checks
- [ ] The code has no (reasonable) Pylint errors
  - In code review, you can decide when fixing a Pylint error is helpful and
    when it's too restricting.
- [ ] Variables are named with snake_case
- [ ] Variable names are clear and helpful
- [ ] The code follows the strategy as simply as possible
- [ ] The implementation is as simple as possible given the strategy
- [ ] The code includes defensive assertions
- [ ] Defensive assertions include as little logic as possible

2024-12-29 13:23 UTC, Awaab98 commented
Hello @Allukmon, I will take on the review process for this implementation.

2024-12-29 16:17 UTC, Allukmon commented
Thanks a lot

2024-12-29 16:27 UTC, Allukmon commented
Thanks a lot Awaab > Hello @Allukmon, I will take on the review process for this implementation.

2024-12-31 20:26 UTC, Awaab98 commented
I have started the review process. There are **two issues** that you should address. Firstly, I checked the **files changed** section in the pull request. You have only added the function python file, and sill remains the test file. Additionally, the function file is empty and you need to push your latest locall implementation to your local branch and then update the pull request. Secondly, after you finished writing the function and the test files, run **ruff format path/to/file.py** command on your CLI to pass the 2 remaining the CI checks related to py_formating.

2025-01-06 15:06 UTC, Allukmon commented
@Awaab98  thanks for your help, I have been able to pass all the CI-checks

2025-01-06 19:34 UTC, Awaab98 commented
Ok. Now that you have passed the CI checks, lets start reviewing your test and function python files.

2025-01-07 18:27 UTC, Allukmon commented
please go ahead with the review

2025-01-11 13:11 UTC, Allukmon commented
@Awaab98 you might want to show me where you made the suggestion because I can not find it on the file I am working on

2025-01-11 13:25 UTC, Awaab98 requested changes
Please review the suggested changes.

2025-01-11 13:38 UTC, Allukmon commented on solutions/find_maximum_value.py
> +    # trunk-ignore(bandit/B101)
It is to ignore the error on the line; I have removed it

2025-01-11 13:39 UTC, Allukmon commented on solutions/find_maximum_value.py
> +        AssertionError: if input is not a list or a non-numerical data
Thanks for pointing that out

2025-01-11 14:22 UTC, Awaab98 approved these changes

2025-01-11 14:22 UTC, merged